In [1]:
import numpy as np
arr=np.array([20,30,40])
print(arr[0])
print(arr[2])

20
40


In [2]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr[1:5])
#python see as like include the start and exclude the end 

[20 30 40 50]


In [7]:
import numpy as np 
arr=np.array([[10,20,30],[60,50,70]])
print(arr[0])
print(arr[:,1])

[10 20 30]
[20 50]


In [8]:
import numpy as np 
arr=np.array([[10,20,30],[60,50,70]])
print(arr[0][1])
print(arr[0,1])
print(arr[1,2])

20
20
70


In [4]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90])
print(arr[:2])
print(arr[2:])
print(arr[::2])

[10 20]
[30 40 50 60 70 80 90]
[10 30 50 70 90]


In [9]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr.reshape(2,3))

[[10 20 30]
 [40 50 60]]


In [11]:
import numpy as np
marks=np.array([40,50,60,70,90])
passing_marks=marks[marks>=50]
print(passing_marks)

[50 60 70 90]


In [12]:
#using the numpy building the mini ml predicting model using the linear regression 

import numpy as np
hours=np.array([1,2,3,4,5,6])
marks=np.array([30,40,50,60,70])
slope=(marks[-1]-marks[0])/(hours[-1]/hours[0])
intercept=marks[0]-slope*hours[0]
new_hours=6
predicted_marks=slope*new_hours+intercept
print("predicted marks for 6 hours is:",predicted_marks)

predicted marks for 6 hours is: 63.33333333333333
