In [1]:
import numpy as np
arr=np.array([1,2,3])
print(arr+5)

[6 7 8]


In [2]:
import numpy as np 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)

[5 7 9]


In [4]:
import numpy as np
arr=np.array([[1,2],[3,4]])
print(arr*3)

[[ 3  6]
 [ 9 12]]


In [6]:
import numpy as np
arr1=np.array([2,3])
arr2=np.array([2,4])
print(np.dot(arr1,arr2))

16


In [7]:
import numpy as np
arr1=np.array([[2,3],[6,7]])
arr2=np.array([[2,4],[2,5]])
print(np.dot(arr1,arr2))

[[10 23]
 [26 59]]


In [11]:
import numpy as np
marks=np.array([80,90,70])
weights=np.array([0.5,0.3,0.3])
print(marks+5)
print(np.dot(marks,weights))

[85 95 75]
88.0
