In [2]:
import numpy as np
arr=np.array([10,20,30])
print(arr+5)

[15 25 35]


In [4]:
import numpy as np
arr=np.array([10,20,30])
print(arr)

[10 20 30]


In [5]:
import numpy as np
arr=np.array([10,20,30])
print(arr)
print(type(arr))


[10 20 30]
<class 'numpy.ndarray'>


In [6]:
import numpy as np
arr=np.array([10,20,30],[40,50,60])
print(arr2)
print(arr.shape)

TypeError: Field elements must be 2- or 3-tuples, got '40'

In [7]:
import numpy as np
arr=np.array([[10,20,30],40,50,60]])
print(arr)
print(arr.shape)

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (2685418598.py, line 2)

In [8]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(arr.shape)

[[10 20 30]
 [40 50 60]]
(2, 3)


In [9]:
import numpy as np
arr=np.array([10,20,30])
print(arr+5)
print(arr*5)

[15 25 35]
[ 50 100 150]


In [10]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))

210
35.0
60
